### PR TITLE
Fixed bug where right calendar would not move unexpectedly when selecting a preset date range

### LINKED ISSUE #74: Selecing a preset date range larger than a month can put the date picker into a weird visual state
#### What I did:
* https://innologica.github.io/vue2-daterange-picker/#example-playground
* Left all defaults options as they were
* I selected the "This year" preset date range

#### What I expected:
* One of the following:
  * If linked: The left calendar to move to the month containing the start date, and the right to move to the following month.
  * If not linked: The left calendar to move to the month containing the start date, and the right calendar to move to the month containing the end date (or the next month if start and end are in the same month).
I'm not entirely sure if what I'm describing above is the actual desired behavior or not, but what actually happens (described next) doesn't align at all with what I expect.

#### What happened instead:
* The left calendar moved to the month containing the start date.
* The right calendar did not move at all.

This resulted in a weird situation where, even when `linkedCalendars` is set to true, the calendars suddenly become unlinked.

#### What I think the problem is:
* In the function below...
https://github.com/Innologica/vue2-daterange-picker/blob/bb9c8291a3f6166058faebde0a324f9457ca1f53/src/components/DateRangePicker.vue#L424-L430
... a value is assigned to `this.monthDate`, but no value is assigned to `this.nextMonthDate`.
* I think the thing we should be doing here instead is passing the value to `this.changeLeftMonth()`. It still doesn't necessarily behave in an expected way when the calendar is unlinked, but it's certainly an improvement.

---

I'll raise PR with a fix described by the line above, in case you're happy with that solution.

### PR DESCRIPTION
**Pull request by iadcode**
Fixes #74

### CODE REVIEW

**Comment by josefryzi** [comment]
@nkostadinov please merge, need this feature, thanks!

**Comment by failbottt** [comment]
> @nkostadinov please merge, need this feature, thanks!

Agreed.

**Comment by andyghiuta** [comment]
Thanks! 
npm publish?

**Comment by nkostadinov** [comment]
sure, i'm just reviewing other PRs so I can push them all at once

**Pull request merged**
