### PR TITLE
BREAKING CHANGE: optional libs separated #166

### PR DESCRIPTION
**Pull request by ggondim**
## Problem

Moment.js and date-fns were being bundled into `vue2-daterange-picker` dist files, including its locales, causing a major library size.

As I commented in #166, this happens because:

> Apparently the file [src/components/util.js](https://github.com/Innologica/vue2-daterange-picker/blob/master/src/components/util.js#L5) does a dynamic `require` but when the library is built it is packaged alongside this other libraries. Even when specified as `optionalDependencies` and `peerDependencies`, modules are imported in utils' files and these options don't affect the final bundle because dynamic `require` can't be determined as "tree-shakeable". 

## Proposed solution

Two separated npm packages were created, `@vue2-daterange-picker/moment` and `@vue2-daterange-picker/date-fns`.

These packages just export the original [date_util/moment.js](https://github.com/Innologica/vue2-daterange-picker/blob/master/src/components/date_util/moment.js) and [date_util/date-fns.js](https://github.com/Innologica/vue2-daterange-picker/blob/master/src/components/date_util/date-fns.js).

Users can still use them as objects, but now adding them as separate dependencies and requiring them:

```
$ npm i -S vue2-daterange-picker @vue2-daterange-picker/moment
```

```javascript
import dateFnsUtil from '@vue2-daterange-picker/moment';

export default {
  data: () => ({
    dateFnsUtil
  })
}
```

```html
<date-range-picker :date-util="dateFnsUtil">
   ...
</date-range-picker>
```

## Results

This solution **reduces bundled file size in ~78%**.

In screenshots below, the same built UMD file was reduced from 861KB to 184KB.

 **Before**:
image

**After**:
image

## Highlights

- Although reducing dist files, this solution makes the package more unopionated
- I published the packages under a `@vue2-daterange-picker` organization in npm, and **added @nkostadinov as member and as owner**, so you can publish new editions.
- A working version of this implementation is published under [@ggondim-org/vue2-daterange-picker](https://www.npmjs.com/package/@ggondim-org/vue2-daterange-picker) that I will unpublish as soon this PR is merged
- ⚠**This introduces a breaking change, the package should have a Major version bumped before this PR is merged**.
- `optionalDependencies` were removed in `package.json`, but a `peerDependencies` pointing to the additional packages was added.
- Also, the `src` folder was removed from `files` in package.json, as they are not needed when installing the package.

## Future improvements

- Docs should be updated removing the `date-util` string option and explaining users how to use these additional packages
- As I said in #166, I think `dateformat.js` also needs to be externalized using it's [npm package](https://www.npmjs.com/package/dateformat) to be optimized
- Probably the `lib` command could be improved applying minification

### CODE REVIEW

**Comment by hmaesta** [comment]
Bundlephobia says that @ggondim-org's package has [62.6 kB minified](https://bundlephobia.com/result?p=@ggondim-org/vue2-daterange-picker@0.5.1). Is that right? This is just incredible – even more because the original package is huge.

**Comment by nkostadinov** [comment]
Hi, thanks for the work on the lib. 

My roadmap is to remove the moment and date-fns completely leaving only the native implementation. Also removing the date-util prop. All date libraries support the native date object so I think this is the best solution.

**Comment by ggondim** [comment]
@nkostadinov great! But is good to offer developers to use these libraries too... Most of people use either moment or date-fns nowadays.

**Comment by nkostadinov** [comment]
> @nkostadinov great! But is good to offer developers to use these libraries too... Most of people use either moment or date-fns nowadays.

I dont see a problem to use any of the other libraries, they all support date object and timestamps. with a simple computed prop with set/get methods you can use any lib you want. The extension internally is agnostic of the library used. This way the extensions will become much lighter and easier to maintain.

**Comment by zhnoah** [comment]
hi, @nkostadinov, any progress? The moment.js problem is still bothering me.

**Comment by nkostadinov** [comment]
removed the ext libs

**Pull request closed without merging**
