### PR TITLE
Add more features: singleDatePicker, timePicker, autoApply, showDropdowns and responsive layout; also with some bugs fixed.

### PR DESCRIPTION
**Pull request by huadong**
Add features: 
- singleDatePicker
- timePicker
- autoApply
- showDropdowns
- autoApply
- reponsive layout base BS4

Some snapshots:
1. showDropdowns, timePicker...
image

2. reponsive
image

image

3. singleDatePicker, autoApply
image

### CODE REVIEW

**Comment by hirenvadalia** [comment]
@huadong and @nkostadinov Any plan to merge this? I want to use this component but I need timePicker also along with DateRangePicker.

**Comment by a-iafrate** [comment]
please merge this pr

**Comment by nkostadinov** [comment]
I'm on a vacation till the end of the week. When I come back I will test it and if it's ok I'll merge it.

**Comment by MrCrankHank** [comment]
Any news? Thanks.

**Comment by nkostadinov** [comment]
I'm currently testing the changes. There are some issues though - if you dont specify min/max Date the component is not working.

**Comment by CesarBMartinez** [comment]
Hello Guys!

Any news about this PR?

**Comment by thubold** [comment]
Hey,
any news about the latest merge conflicts?

**Comment by Ganssy** [comment]
Please  accept this PR i need options

**Comment by huadong** [comment]
this dependency in package.json works fine for me:

> "vue2-daterange-picker": "https://github.com/huadong/vue2-daterange-picker.git#dist"

**Pull request merged**
